### ISSUE TITLE
Simplify the window.onload so you don't need to have your whole program inside of it

### ISSUE THREAD

**Issue by emiliogomezlavin** [mnorelli/tic-tac-toe#1]
Hello!

First of all, congrats on the awesome job! The CSS looks amazing and I love the creativeness of the sounds and the cleaness of the look. Logic wise I also think it's a great approach to solving the issue at hand and it's very similar to what I did but with way clearer code. So I know usually you'd get simpler text messages with the actual issue but I wanted to compliment your work first  :) 

I am leaving an easy issue and a more complex challenge but I believe you'll be able to do both. 

First the easy:

**Issue:  Could you call the window.onload function without needing to have all your code inside of it? It can be confusing if something gets left out**

**Comment by mnorelli** [comment]
Fixed by moving everything except the _resetBoard()_ function out of the onload listener.  (No longer need the _startGame()_ function, as a result.) Great feedback!  Much less prone to error now.
